### ISSUE TITLE
Failure to validate bounty before submission

### ISSUE THREAD

**Issue by musingsole** [MakUrSpace/hyperspace#19]
Error:
```
2021-08-05T09:52:00.668-04:00 - [ERROR] AttributeError: 'NoneType' object has no attribute 'string'
Traceback (most recent call last):
  File "/var/task/hyperspace/api.py", line 72, in lambda_handler
    results = page.handle_request(event)
  File "/var/task/LambdaPage/LambdaPage.py", line 33, in handle_request
    resp = func(event)
  File "/var/task/hyperspace/bounty_system/bounty_creation.py", line 62, in submit_bounty_form
    send_bounty_to_contact(new_bounty)
  File "/var/task/hyperspace/bounty_system/bounty_creation.py", line 35, in send_bounty_to_contact
    contact=new_bounty.sanitized_contact, content=email_template)
  File "/var/task/hyperspace/objects.py", line 50, in sanitized_contact
    return sanitize_email(self.Contact)
  File "/var/task/hyperspace/utilities.py", line 41, in sanitize_email
    return regexed.string
```

**Comment by musingsole** [comment]
Addressed in commit a2c3406fd93c9437c74073d5a99f166959baf416
